window.doiDuocData = [
  { doiduoc: "Ma hoàng – Quế chi", chutri: "Thái dương thương hàn chứng; Tý chứng do phong hàn thấp; Ho suyễn do phong hàn" },
  { doiduoc: "Kinh giới – Phòng phong", chutri: "Cảm mạo tứ thời; Ban chẩn có ngứa; Loét mới khởi phát; Tiện huyết, cường kinh, tiêu chảy, lỵ" },
  { doiduoc: "Thông bạch – Đạm đậu xị", chutri: "Ngoại cảm giai đoạn đầu, tà ở vệ phận" },
  { doiduoc: "Tang diệp – Tang chi", chutri: "Ngoại cảm phong nhiệt mới mắc; Tý chứng do phong thấp nhiệt; Ban chẩn ngứa do phong nhiệt" },
  { doiduoc: "Chi tử – Đạm đậu xị", chutri: "Ngoại cảm phong nhiệt; Ôn bệnh mới mắc; Giai đoạn phục hồi của nhiệt bệnh, dư nhiệt chưa trừ hết, gây ngực phiền, bứt rứt không yên, mất ngủ" },
  { doiduoc: "Hạnh nhân – Đâu xị", chutri: "Ngoại cảm biểu chứng, bất kể hàn nhiệt, có ho đều có thể dùng được; Ôn bệnh tại vệ phận có ho" },
  { doiduoc: "Tang diệp – Cúc hoa", chutri: "Cảm mạo phong nhiệt có ho, miệng khát; Can dương thượng nhiễu gây mắt đỏ đau" },
  { doiduoc: "Kim ngân hoa – Liên kiều", chutri: "Cảm mạo phong nhiệt, ôn bệnh mới mắc; Ngứa do phong nhiệt; Lở loét, áp xe, ung nhọt" },
  { doiduoc: "Câu đằng – Bạc hà", chutri: "Cảm mạo phong nhiệt, ôn bệnh mới mắc; Ho do nội thương, ngoại cãm, lâu ngày không khỏi; Phong nhiệt thượng nhiễu gây đau đầu, nhìn mờ; Can dương thượng nhiễu gây đau đầu, chóng mặt; Trẻ em ngủ không yên, kinh sợ khóc đêm" },
  { doiduoc: "Mạn kinh tử - Liên kiều", chutri: "Phong nhiệt gây đau đầu; Phong hỏa đầu thống; Đau mắt đỏ cấp tính" },
  { doiduoc: "Cương tàm – Kinh giới tuệ", chutri: "Cảm mạo phong hàn; Phong chẩn gây ngứa da; Thất âm sau trúng phong; Băng lậu" },
  { doiduoc: "Cát căn – Thăng ma", chutri: "Ban chẩn mới khởi phát; Sởi chậm phát ban" },
  { doiduoc: "Phù bình – Tử thảo", chutri: "Trẻ em mới mắc sởi, ban chẩn chưa phát ra hết; Phong chẩn, phong nhiệt gây ngứa ngoài da; Ung nhọt lở loét do phong nhiệt" },
  { doiduoc: "Phù bình – Ngưu bang tử", chutri: "Ngoại cảm phong nhiệt có sưng đau họng; Sởi chưa phát ban hết; Ngứa da do phong nhiệt tà" },
  { doiduoc: "Thuyền thoái – Bạc hà", chutri: "Ban chẩn do phong nhiệt; Sởi thời kỳ đầu, ban chẩn chưa mọc hết; Ngứa da do phong nhiệt; Trẻ em khóc đêm (dạ đề)" },
  { doiduoc: "Bạch tật lê – Kinh giới tuệ", chutri: "Ngứa da do phong tà" },
  { doiduoc: "Kim ngân hoa – Nhẫn đông đằng", chutri: "Ôn bệnh giai đoạn đầu, cảm mạo phong nhiệt; Phong thấp nhiệt tý; Da lở loét, sưng đỏ" },
  { doiduoc: "Bạch mao căn – Lô căn", chutri: "Cảm mạo, ôn bệnh phát sốt giai đoạn đầu; Phế nhiệt gây khái suyễn; Ma chẩn giai đoạn đầu (giúp thấu chẩn); Nấc do nhiệt; Nhiễm trùng tiểu" },
  { doiduoc: "Tri mẫu – Thạch cao", chutri: "Ngoại cảm phong hàn hóa nhiệt, ôn nhiệt nhập Phế Vị; Đái tháo đường" },
  { doiduoc: "Tiên địa hoàng – Can địa hoàng", chutri: "Nhiệt nhập dinh huyết phận; Huyết nhiệt vọng hành; Âm hư huyết nhiệt" },
  { doiduoc: "Can địa hoàng – Bạch mao căn", chutri: "Nhiệt nhập dinh huyết; Huyết nhiệt vọng hành; Sốt âm ỉ không rõ nguyên nhân" },
  { doiduoc: "Tiên địa hoàng – Thạch hộc", chutri: "Sốt cao gây thương âm; Ôn bệnh giai đoạn sau; Vị âm hư gây chán ăn" },
  { doiduoc: "Nam sa sâm – Bắc sa sâm", chutri: "Nhiệt bệnh thương tân; Phế âm hư gây ho mạn tính" },
  { doiduoc: "Qua lâu bì – Thiên hoa phấn", chutri: "Ho do Phế táo; Nhiệt bệnh thương âm gây khí nghịch, tức ngực" },
  { doiduoc: "Xích thược – Bạch thược", chutri: "Nhiệt nhập huyết phận gây mắt đỏ; Âm hư tân khuy; Ngực sườn đau, bụng đầy đau; Kinh nguyệt không đều, bế kinh" },
  { doiduoc: "Thiên môn – Mạch môn", chutri: "Âm hư triều nhiệt; Nhiệt thương phế lạc gây khái huyết; Đái tháo đường; Phế âm hư gây ho mạn tính" },
  { doiduoc: "Miết giáp – Quy bản", chutri: "Âm hư phát nhiệt gây cốt chưng, triều nhiệt, phế lao; Âm hư phong động gây co giật; Âm hư dương kháng gây chóng mặt, đau đầu, ù tai; Bế kinh do âm hư" },
  { doiduoc: "Thanh hao – Miết giáp", chutri: "Âm hư phát nhiệt; Sốt rét; Ôn bệnh giai đoạn hồi phục, âm hư chưa khôi phục hoàn toàn; Sốt âm ỉ chưa rõ nguyên nhân" },
  { doiduoc: "Tri mẫu – Hoàng bá", chutri: "Âm hư phát nhiệt gây cốt chưng, triều nhiệt, đạo hãn; Âm hư hỏa vượng gây di tinh, mộng tinh, hoạt tinh; Tăng libido cả nam và nữ" },
  { doiduoc: "Can địa hoàng – Thục địa hoàng", chutri: "Nhiệt bệnh thương âm, sốt âm ỉ kéo dài; Âm hư phát nhiệt gây cốt chưng, triều nhiệt; Can Thận bất túc gây chóng mặt, mất ngủ, tâm quý; Đái tháo đường" },
  { doiduoc: "Tri mẫu – Thạch cao", chutri: "Ngoại cảm phong hàn hóa nhiệt, ôn nhiệt nhập Phế Vị; Đái tháo đường" },
  { doiduoc: "Hoàng cầm – Hoàng liên", chutri: "Thượng, trung tiêu nhiệt thịnh gây mắt đỏ, răng lợi sưng đỏ đau, miệng lưỡi loét; Sốt cao bứt rứt; Mụn nhọt sưng đỏ đau; Hội chứng mãn kinh có sốt; Lỵ do thấp nhiệt; Đái tháo đường có táo nhiệt" },
  { doiduoc: "Thương truật – Hoàng bá", chutri: "Thấp nhiệt hạ chú gây đau chi dưới; Thấp nhiệt gây lâm chứng; Viêm khớp dạng thấp, hồng ban dạng nút" },
  { doiduoc: "Tử hoa địa đinh – Bồ công anh", chutri: "Đinh nhọt sưng đỏ đau; Nhiễm trùng tiểu; Nhiễm trùng có mủ ngoài da" },
  { doiduoc: "Ngưu bàng tử - Liên kiều", chutri: "Nhiệt ở thượng tiêu gây lở loét miệng lưỡi, họng sưng đỏ đau; Nhọt lở loét; Phong nhiệt phát ra ban chẩn, ngứa da" },
  { doiduoc: "Mã bột – Thanh đại", chutri: "Sưng đau họng do hỏa độc thượng tiêu; Viêm họng cấp và mạn" },
  { doiduoc: "Mã bột – Đại cáp tán", chutri: "Nhiệt ở thượng tiêu gây sưng đau họng, hạch; Can hỏa phạm Phế gây ho khan mạn tính, ho ra máu" },
  { doiduoc: "Bản lam căn – Sơn đậu căn", chutri: "Sưng đau họng; Lở loét miệng lưỡi" },
  { doiduoc: "Bản lam căn – Huyền sâm", chutri: "Âm hư hỏa vượng gây sưng đau họng" },
  { doiduoc: "Thạch cao – Tế tân", chutri: "Tà nhiệt nội uẩn gây đau răng, nướu, loét miệng lưỡi; Cảm phong nhiệt phạm thanh khiếu" },
  { doiduoc: "Tế tân – Can địa hoàng", chutri: "Phong hỏa gây đau đầu, đau răng; Âm hư, hư hỏa thượng nhiễu" },
  { doiduoc: "Hoắc hương – Bội lan", chutri: "Trúng thử gây đau đầu, chóng mặt, ngực bụng đầy tức, tiêu lỏng, buồn nôn, nôn" },
  { doiduoc: "Hoạt thạch – Cam thảo", chutri: "Trúng thử; Lâm chứng; Sỏi tiết niệu" },
  { doiduoc: "Xa tiền tử - Lục nhất tán", chutri: "Trúng thử; Lâm chứng; Sỏi tiết niệu" },
  { doiduoc: "Lục nhất tán – Hà diệp", chutri: "Trúng thử; Niệu huyết" },
  { doiduoc: "Lục nhất tán – Đăng tâm thảo", chutri: "Trúng thử; Lâm chứng" },
  { doiduoc: "Xa tiền tử - Xa tiền thảo", chutri: "Lỵ do thử nhiệt; Lâm chứng; Sỏi tiết niệu" },
  { doiduoc: "Bạch thược – Quế chi", chutri: "Ngoại cảm phong hàn biểu hư chứng; Tự hãn, đạo hãn do dinh vệ bất hòa, Tâm huyết hư, Tỳ Phế hư; Hung tý, hung thống do Tâm dương hư, khí huyết thất điều; Phúc thống do hư hàn; Tứ chi đau tê do khí huyết không thông điều; Ốm nghén" },
  { doiduoc: "Bạch thược – Sài hồ", chutri: "Hàn nhiệt vãng lai; Chóng mặt, đau tức ngực sườn do Can khí uất; Kinh nguyệt không đều" },
  { doiduoc: "Sài hồ - Hoàng cầm", chutri: "Thiếu dương chứng; Ngược tật; Can khí uất hóa hỏa" },
  { doiduoc: "Hoàng cầm – Bán hạ", chutri: "Tà ở thiếu dươnf dùng nhầm phép hạ thành chứng bĩ; Đàm nhiệt hỗ kết gây đầy chướng bụng, chán ăn, buồn nôn; Tăng tiết acid dạ dày" },
  { doiduoc: "Tri mẫu – Thảo quả", chutri: "Hàn nhiệt vãng lai; Ngược tật" },
  { doiduoc: "Thường sơn – Thảo quả", chutri: "Ngược tật" },
  { doiduoc: "Hoàng kỳ - Phòng phong", chutri: "Biểu hư tự hãn; Dễ cảm mạo" },
  { doiduoc: "Sơn thù – Mẫu lệ", chutri: "Tự hãn, đạo hãn; Di tinh, hoạt tinh; Đới hạ; Đái tháo đường" },
  { doiduoc: "Ma hoàng căn – Phù tiểu mạch", chutri: "Khí hư tự hãn; Âm hư đạo hãn" },
  { doiduoc: "Hoàng kỳ - Mẫu lệ", chutri: "Khí âm bất túc gây tự hãn, đạo hãn" },
  { doiduoc: "Hoàng kỳ - Phù tiểu mạch", chutri: "Biểu hư tự hãn" },
  { doiduoc: "Ngũ vị tử - Ngũ bội tử", chutri: "Tự hãn, đạo hãn; Phế khí hư gây ho mạn tính; Tiêu chảy mạn tính; Di hoạt tinh, băng lậu; Sa tạng phủ" },
  { doiduoc: "Hoàng kỳ - Phụ tử", chutri: "Dương hư tự hãn kèm tứ chi lạnh" },
  { doiduoc: "Ô mai – Ngũ vị tử", chutri: "Tự hãn, đạo hãn; Đái tháo đường" },
  { doiduoc: "Khiếm thực – Liên tử", chutri: "Tỳ hư tiết tả; Tỳ hư thấp thịnh gây bạch đới; Thận hư bất cố gây hoạt tinh, di tinh, mộng tinh; Thận hư gây tiểu nhiều lần, tiểu không tự chủ" },
  { doiduoc: "Sơn dược – Biển đậu", chutri: "Tỳ Vị hư nhược gây tiết tả; Đới hạ do Tỳ hư" },
  { doiduoc: "Mộc hương – Hoàng liên", chutri: "Xích bạch lỵ" },
  { doiduoc: "Tả kim hoàn – Tàm sa", chutri: "Thấp nhiệt gây trường vị thất chức sinh tiết tả; Lỵ mạn tính" },
  { doiduoc: "Cát cánh – Hạnh nhân", chutri: "Lỵ tật giai đoạn đầu" },
  { doiduoc: "Binh lang – Nam qua tử", chutri: "Sán dây" },
  { doiduoc: "Nha đảm tử - Long nhãn nhục", chutri: "Lỵ tật" },
  { doiduoc: "Xuyên tiêu – Thương truật", chutri: "Hàn thấp nội uẩn gây ngực bụng đau, tiết tả; Hàn thấp đới hạ" },
  { doiduoc: "Nhục đậu khấu – Bổ cốt chỉ", chutri: "Tỳ Thận dương hư gây tiết tả; Ngũ canh tả" },
  { doiduoc: "Xích thạch chi – Vũ dư lương", chutri: "Thương hàn hạ lỵ không cầm; Viêm ruột mạn tính, lỵ mạn tính; Cửu tả, cửu lỵ gây thoát giang; Tiện huyết hư hàn; Cường kinh, xích bạch đới do hư hàn" },
  { doiduoc: "Huyết dư than – Vũ dư lương", chutri: "Cửu tả, cửu lỵ" },
  { doiduoc: "Xích thạch chi – Bạch thạch chi", chutri: "Cửu tả, cửu lỵ; Tiện huyết; Cường kinh, băng lậu, đới hạ; Di tinh" },
  { doiduoc: "Kim anh tử - Khiếm thực", chutri: "Tỳ Thận dương hư gây tiết tả mạn; Thận khí bất cố gây di tinh, đới hạ" },
  { doiduoc: "Tang phiêu tiêu – Hải phiêu tiêu", chutri: "Thận khí hư gây tiểu nhiều lần, tiểu không tự chủ; Trẻ em đái dầm; Di tinh, tảo tiết, băng lậu, đới hạ" },
  { doiduoc: "Phục linh – Ích trí nhân", chutri: "Tỳ Thận hư gây tiết tả" },
  { doiduoc: "Thương truật – Phòng phong", chutri: "Tiết tả phân lỏng như nước; Tiêu phân sống" },
  { doiduoc: "Thuyền thoái – Phụng hoàng y", chutri: "Khàn tiếng" },
  { doiduoc: "Kha tử - Quất bì", chutri: "Khàn tiếng, cảm giác khó chịu ở họng" },
  { doiduoc: "Kha tử - Cát cánh – Cam thảo", chutri: "Khàn tiếng, mất tiếng; Viêm họng mãn tính; Nốt dây thanh" },
  { doiduoc: "Thạch xương bồ - Thuyền thoái", chutri: "Chóng mặt, ù tai" },
  { doiduoc: "Từ thạch – Thạch xương bồ", chutri: "Thận âm hư, hư hỏa thượng nhiễu gây ù tai; Âm hư dương kháng gây chóng mặt, đau đầu, mất ngủ" },
  { doiduoc: "Thương nhĩ tử - Tân di", chutri: "Cảm phong hàn gây nghẹt mũi, chảy mũi; Viêm mũi xoang mạn tính, viêm mũi dị ứng" },
  { doiduoc: "Phù hải thạch – Toàn phúc hoa", chutri: "Ho do đàm nhiệt, đàm khó khạc, nặng ngực" },
  { doiduoc: "Bán hạ khúc – Toàn phúc hoa", chutri: "Khái thấu do đàm thấp; Chi ẩm gây đoản khí, ngực đầy tức" },
  { doiduoc: "Đại cáp tán – Phù hải thạch", chutri: "Đàm hỏa uất kết gây đau ngực sườn, khái thấu, suyễn; Ho khạc đàm mạn tính; Giãn phế quản" },
  { doiduoc: "Tỳ bà diệp – Bán hạ", chutri: "Khái thấu khí suyễn lâu ngày không khỏi" },
  { doiduoc: "Đởm nam tinh – Toàn phúc hoa", chutri: "Ho khạc đàm lâu ngày do dàm thấp trở phế; Đàm ứ trệ kinh lạc gây tay chân tê" },
  { doiduoc: "Thiên trúc hoàng – Bán hạ khúc", chutri: "Thấp nhiệt nội ủng gây ho khạc đàm, tức ngực" },
  { doiduoc: "Quất hồng – Quất lạc", chutri: "Ho khạc đàm nhiều, kèm tức ngực" },
  { doiduoc: "Tử uyển – Quất hồng", chutri: "Đàm trở hung cách gây ho, tức ngực; Ho do ngoại cảm, nội thương, hàn, nhiệt đều dùng được" },
  { doiduoc: "Bạch tiền – Tiền hồ", chutri: "Ho do Phế khí không tuyên, thanh túc thất chức" },
  { doiduoc: "Bạch tiền – Bách bộ", chutri: "Cảm mạo lâu ngày gây Phế khí thượng nghịch mà ho; Ho do Phế lao" },
  { doiduoc: "Bán hạ - Quất bì", chutri: "Đàm thấp nội đình gây ho khạc đàm, tức ngực" },
  { doiduoc: "Hạnh nhân – Xuyên bối mẫu", chutri: "Ho do Phế âm hư; Ngoại cảm phong tà, đàm nhiệt uất Phế" },
  { doiduoc: "Tri mẫu – Xuyên bối mẫu", chutri: "Ho do âm hư; Ho do Phế nhiệt" },
  { doiduoc: "Qua lâu tử - Qua lâu bì", chutri: "Ho do đàm nhiệt" },
  { doiduoc: "Tỳ bà diệp – Lục nhất tán", chutri: "Phế nuy, Phế ung" },
  { doiduoc: "Ma hoàng – Anh túc xác", chutri: "Ho mạn tính làm Phế khí mất thu liễm" },
  { doiduoc: "Nhân sâm – Tam thất", chutri: "Ho do hư lao" },
  { doiduoc: "A giao – Tử uyển", chutri: "Ho lâu ngày, ho ra máu dp Phế âm hư; Giãn phế quản" },
  { doiduoc: "Mộc qua – Thanh đại", chutri: "Ho; Đau gân gót" },
  { doiduoc: "Ngũ vị tử - Tế tân", chutri: "Ho do phong hàn, đàm ẩm; Phế Thận lưỡng hư gây ho mạn tính" },
  { doiduoc: "Ngũ vị tử - Can khương", chutri: "Ho do Phế có hàn" },
  { doiduoc: "Tô tử - Tử uyển", chutri: "Ho suyễn khạc đàm kèm tức ngực; VPQM; Hen phế quản" },
  { doiduoc: "Lai bặc tử - Bạch giới tử", chutri: "Ho ở người già, hư nhược; Ho suyễn mạn tính" },
  { doiduoc: "Đình lịch tử - Đại táo", chutri: "Đàm thủy ủng Phế gây ho suyễn, phù thũng" },
  { doiduoc: "Xạ can – Ma hoàng", chutri: "Đàm trọc ủng thịnh tắc khí đạo gây háo suyễn; VPQM; Hen phế quản" },
  { doiduoc: "Sơn dược – Ngưu bàng tử", chutri: "Tỳ hư không kiện vận, Phế khí hư  đám thấp nội sinh" },
  { doiduoc: "Quất bì – Tang bạch bì", chutri: "Ho do Phế nhiệt" },
  { doiduoc: "Tang bạch bì – Địa cốt bì", chutri: "Ho suyễn do Phế nhiệt, phong ôn; Thủy thũng" },
  { doiduoc: "Tang bạch bì – Tang diệp", chutri: "Ho do Phế nhiệt" },
  { doiduoc: "Thục địa – Ma hoàng", chutri: "Suyễn lâu ngày không có đàm; Đàm hạch" },
  { doiduoc: "Thục địa – Đương quy", chutri: "Ho suyễn lâu ngày, âm huyết hư suy" },
  { doiduoc: "Đại táo – Hắc tích đơn", chutri: "Ho suyễn lâu ngày; Thận hư không nạp khí sinh ra suyễn; VPQM ; Tâm phế mạn" },
  { doiduoc: "Bổ cốt chỉ - Hồ đào nhân", chutri: "Ho suyễn do Thận hư; Suy nhược mạn, mất ngủ, giảm trí nhớ" },
  { doiduoc: "Thương truật – Huyền sâm", chutri: "Đái tháo đường; Rối loạn lipid máu" },
  { doiduoc: "Hoàng kỳ - Sơn dược", chutri: "Đái tháo đường; Viêm dạ dày mạn thể Tỳ khí hư" },
  { doiduoc: "Lục đậu y – Ý dĩ nhân", chutri: "Thượng tiêu khát" },
  { doiduoc: "Cát căn – Đan sâm", chutri: "Đái tháo đường kèm huyết ứ rõ" },
  { doiduoc: "Huyền sâm – Mạch môn", chutri: "Đái tháo đường với biểu hiện táo nhiệt tân khuy" },
  { doiduoc: "Tri mẫu – Hoàng bá – Nhục quế", chutri: "Đái tháo đường thể hạ tiêu khát" },
  { doiduoc: "Sinh địa – Dâm dương hoắc", chutri: "Đái tháo đường thể Thận âm dương lưỡng hư; Viêm khớp dạng thấp thể âm dương lưỡng hư" },
  { doiduoc: "Kê nội kim – Đan sâm", chutri: "Viêm loét dạ dày tá tràng; Gan lách to; Chán ăn do Vị âm hư, Vị dương bất túc" },
  { doiduoc: "Kê nội kim – Mạch nha", chutri: "Tỳ Vị hư nhược không muốn ăn" },
  { doiduoc: "Ô mai – Mộc qua", chutri: "Ôn bệnh làm khí âm lưỡng hư; Vị âm hư; Viêm loét dạ dày tá tràng; Viêm dạ dày thiểu toan" },
  { doiduoc: "Bội lan – Thạch xương bồ", chutri: "Thấp trệ Tỳ Vị gây vận hóa thất chức" },
  { doiduoc: "Hậu phác hoa – Đại đại hoa", chutri: "Can uất thừa Tỳ" },
  { doiduoc: "Mân côi hoa – Đại đại hoa", chutri: "Can Vị bất hòa gây ăn uống kém, đau hông sườn; Kinh nguyệt không đều, xích bạch đới" },
  { doiduoc: "Thương truật – Bạch truật", chutri: "Thấp trệ trung tiêu gây tiết tả, đầy bụng; Tỳ Vị thất kiện vận gây chán ăn, buồn nôn, nôn" },
  { doiduoc: "Bán hạ khúc – Kiện thần khúc", chutri: "Tỳ Vị hư thất kiện vận" },
  { doiduoc: "Bán hạ khúc – Trầm hương khúc", chutri: "Tỳ Vị hư thất kiện vận" },
  { doiduoc: "Bạch truật – Kê nội kim", chutri: "Tỳ Vị hư thất kiện vận" },
  { doiduoc: "Chỉ thực – Bạch truật", chutri: "Tỳ Vị hư ăn uống kém; Gan lách to" },
  { doiduoc: "Bạch truật – Phục linh", chutri: "Tỳ hư thủy thấp nội đình; Chóng mặt do  bệnh Meniere" },
  { doiduoc: "Bán hạ - Trúc nhự", chutri: "Tỳ Vị bất hòa, Vị khí thượng nghịch gây nôn; Đàm trọc gây huyễn vựng, hư phiền; Thai nghén" },
  { doiduoc: "Chỉ thực – Trúc nhự", chutri: "Đàm nhiệt gây Vị khí nghịch" },
  { doiduoc: "Ngõa lăng tử - Bán hạ khúc", chutri: "Đàm thấp trở trệ trung tiêu gây Vị thất hòa giáng; Làm giảm acid dạ dày" },
  { doiduoc: "Hoàng liên – Ngô thù du", chutri: "Can uất hóa hỏa phạm Vị; Viêm dạ dày cấp và mạn tính; Thấp nhiệt lỵ" },
  { doiduoc: "Tả kim hoàn – Huyết dư thán", chutri: "Can uất hóa hỏa gây nôn chua; Viêm ruột cấp và mạn tính" },
  { doiduoc: "Can khương – Hoàng liên", chutri: "Hàn nhiệt thác tạp, nôn chua, vị thống; Tiết tả, lỵ tật" },
  { doiduoc: "Đinh hương – Thị đế", chutri: "Ách nghịch hàn nhiệt thác tạp; Tỳ Vị hư hàn gây nôn" },
  { doiduoc: "Quất bì – Trúc nhự", chutri: "Tỳ Vị hư nhược, hàn nhiệt thác tạp; Thai nghén" },
  { doiduoc: "Thương truật – Bạch chi ma", chutri: "Nấc cục do Tỳ Vị hư nhược" },
  { doiduoc: "Mã bảo – Trầm hương", chutri: "Nấc cục" },
  { doiduoc: "Đại hoàng – Mang tiêu", chutri: "Vị trường thực nhiệt gây đại tiện táo kết" },
  { doiduoc: "Huyền minh phấn – Qua lâu nhân", chutri: "Táo bón" },
  { doiduoc: "Đại hoàng – Kinh giới tuệ", chutri: "Mắt sưng đỏ đau; Nhị tiện không thông, hậu môn đau" },
  { doiduoc: "Đại hoàng – Nhục quế", chutri: "Can khí uất, Vị khí nghịch gây nôn ra máu; Vị quản thống do hàn nhiệt thác tạp" },
  { doiduoc: "Tàm sa – Tạo giác", chutri: "Huyễn vựng; Bụng đầy đau; Đại tiện lúc đầu cứng sau nát" },
  { doiduoc: "Đương quy đầu – Nhục thung dung", chutri: "Ôn bệnh gây tân khuy mà táo bón; Táo bón ở người già, phụ nữ sau sinh, huyết hư trường táo" },
  { doiduoc: "Quất hồng – Hạnh nhân", chutri: "Táo bón người già, hư nhược; Phế khí thất tuyên gây tức ngực, ho khạc đàm" },
  { doiduoc: "Hỏa ma nhân – Úc lý nhân", chutri: "Táo bón sau nhiệt bệnh, sản hậu, người già, hư nhược; Táo bón tái phát, mạn tính" },
  { doiduoc: "Bán hạ - Lưu hoàng", chutri: "Mệnh môn hỏa suy làm Vị thất hòa giáng mà nấc cục; Người già hư hàn tiện bí; Tiết tả lâu ngày do hàn thấp" },
  { doiduoc: "Thanh bì – Quất bì", chutri: "Can Vị bất hòa gây đau thượng vị; Đau thần kinh liên sườn, viêm gan mạn" },
  { doiduoc: "Chỉ xác – Uất kim", chutri: "Can khí uất gây ngực sườn đau; Viêm gan mạn, xơ gan, viêm túi mật, sỏi mật có đau ngực sườn, ứ huyết rõ" },
  { doiduoc: "Chỉ thực – Chỉ xác", chutri: "Ăn không tiêu, ngực bụng đầy chướng, đại tiện không thông sướng; Sa dạ dày, sa tử cung, thoát giang" },
  { doiduoc: "Hương phụ - Tô ngạnh", chutri: "Ngực bụng đầy chướng; Thai nghén" },
  { doiduoc: "Thanh quất diệp – Uất kim", chutri: "Can khí uất gây hạ sườn đau; Viêm thần kinh liên sườn" },
  { doiduoc: "Giới bạch – Qua lâu", chutri: "Đàm trọc uất bế ở ngực cản trở dương khí thông hành gây ngực đầy, khái suyễn nhiều đàm, đau ngực lan ra sau lưng; Bệnh mạch vành" },
  { doiduoc: "Quất bì – Chỉ thực", chutri: "Tỳ Vị thất kiện vận gây bụng chướng; Viêm loét dạ dày cấp và mạn; Viêm ruột cấp và mạn" },
  { doiduoc: "Quất bì – Trầm hương", chutri: "Ngục bụng đầy chướng do chậm tiêu; Viêm gan mạn" },
  { doiduoc: "Toàn phúc hoa – Đại giả thạch", chutri: "Đàm trọc nội trở gây đầy chướng, ợ hơi, nấc cục; Ho khạc đàm, nôn ra máu, chảy máu cam; Tăng huyết áp" },
  { doiduoc: "Tô ngạnh – Cát cánh", chutri: "Ngực đầy, khí nghịch do khí cơ không thông" },
  { doiduoc: "Tô ngạnh – Hoắc hương ngạnh", chutri: "Thấp trệ trung tiêu gây ngực bụng đầy chướng; Trúng thử gây nôn, tiết tả" },
  { doiduoc: "Cát cánh – Chỉ xác – Giới bạch – Hạnh nhân", chutri: "Ngực bụng đầy chướng, chán ăn; Mai hạch khí; Mất ngôn ngữ" },
  { doiduoc: "Sa nhân – Bạch đậu khấu", chutri: "Tỳ Vị hư hàn, vận hóa thất chức, thấp trọc nội uẩn; Trẻ em tiêu hóa kém, nôn trớ" },
  { doiduoc: "Qua lâu – Chỉ thực", chutri: "Vị quản thống" },
  { doiduoc: "Hương phụ - Ô dược", chutri: "Đau bụng dưới; Viêm gan cấp và mạn; Lý cấp hậu trọng" },
  { doiduoc: "Diên hồ sách – Xuyên luyện tử", chutri: "Can khí uất, Can Đởm hỏa vượng gây đau ngực sườn; Đau BPSD; Thống kinh, kinh nguyệt không đều; Viêm gan, viêm túi mật; Đau ngực do bệnh mạch vành" },
  { doiduoc: "Cao lương khương – Hương phụ", chutri: "Can khí uất, hàn tà phạm Vị gây vị quản thống; Viêm dạ dày mạn thể hàn" },
  { doiduoc: "Lai bặc tử - Lai bặc anh", chutri: "Tỳ Vị bất hòa, tiêu hóa kém, bụng chướng đau" },
  { doiduoc: "Mộc hương – Binh lang", chutri: "Vị trường tích trệ, bụng ngực đầy chướng; Lỵ tật; Tiện bí do liệt nửa người" },
  { doiduoc: "Xuyên luyện tử - Trạch lan", chutri: "Can khí uất gây đau ngực sườn; Kinh nguyệt không đều, bế kinh, thống kinh; Sản hậu ứ huyết, trưng hà" },
  { doiduoc: "Nguyệt quý hoa – Đại đại hoa", chutri: "Can khí uất gây kinh nguyệt không đều, thống kinh" },
  { doiduoc: "Ngải diệp – Hương phụ", chutri: "Can khí uất, hạ tiêu hư hàn gây thống kinh, đới hạ, vô sinh; Vị quản thống" },
  { doiduoc: "Địa cẩm thảo – Phân tâm mộc", chutri: "Ngực đau, chướng đầy; Bệnh mạch vành; Rung nhĩ" },
  { doiduoc: "Đan sâm – Đàn hương", chutri: "Đau ngực do khí trệ huyết ứ; Bệnh mạch vành" },
  { doiduoc: "Giáng hương – Ngũ linh chi", chutri: "Bệnh mạch vành; Đau thần kinh liên sườn" },
  { doiduoc: "Đan sâm – Tam thất", chutri: "Bệnh mạch vành có đau ngực" },
  { doiduoc: "Thạch xương bồ - Uất kim", chutri: "Đau ngực do khí trệ huyết ứ; Bệnh mạch vành" },
  { doiduoc: "A giao – Tiên hạc thảo", chutri: "Các bệnh tim mạch; Bổ huyết sau xuất huyết" },
  { doiduoc: "Địa cẩm thảo – Tiên hạc thảo", chutri: "Nhịp tim nhanh" },
  { doiduoc: "Khương hoạt – Cúc hoa", chutri: "Đau thắt ngực do bệnh mạch vành" },
  { doiduoc: "Đào nhân – Hạnh nhân", chutri: "Khí trệ huyết ứ gây đau ngực, bụng; Táo bón ở người già, hư nhược; Nuốt nghẹn; Ho do viêm phế quản mạn" },
  { doiduoc: "Đan bì – Đan sâm", chutri: "Ban chẩn do phong nhiệt; Huyết nhiệt gây kinh nguyệt không đều, bế kinh, thống kinh; Âm hư phát nhiệt; Nhiệt tý" },
  { doiduoc: "Tam lăng – Nga truật", chutri: "Huyết ứ gây bế kinh, thống kinh, trưng hà tích tụ; Gan lách to; Thực tích đau bụng; Ung thư vùng bụng" },
  { doiduoc: "Nhũ hương – Một dược", chutri: "Khí huyết ứ trệ gây đau bụng, bế kinh, thống kinh, đau bụng sau sinh; Chấn thương, phong thấp tý; Đau thắt ngực; Viêm vùng chậu" },
  { doiduoc: "Hoa nhụy thạch – Chung nhũ thạch", chutri: "Ho ra máu do tổn thương phổi; Chảy máu cam, nôn ra máu, băng lậu" },
  { doiduoc: "Tam thất – Bạch cập", chutri: "Ho ra máu do tổn thương phổi; Nôn ra máu, tiểu máu, tiêu ra máu, chảy máu cam" },
  { doiduoc: "Bồ hoàng – Ngũ linh chi", chutri: "Khí trệ huyết ứ gây đau ngực bụng; Kinh nguyệt không đều, thống kinh, sau sinh sản dịch chưa ra hết" },
  { doiduoc: "Đương quy – Xuyên khung", chutri: "Kinh nguyệt không đều, thống kinh, sinh khó, sau sinh sản dịch chưa ra hết; Các chứng lở loét sưng đau; Phong thấp tý; Huyết hư, huyết ứ gây đau đầu" },
  { doiduoc: "Đào nhân – Hồng hoa", chutri: "Tâm huyết ứ gây đau ngực; Huyết ứ gây bế kinh, thống kinh; Huyết ứ gây đau" },
  { doiduoc: "Đại hoàng – Thổ miết trùng", chutri: "Huyết ứ gây bế kinh, tích khối, cơ nhục teo; Chấn thương huyết ứ gây đau" },
  { doiduoc: "Đại hoàng – Thăng ma", chutri: "Nôn ra máu; Băng lậu" },
  { doiduoc: "Hải phiêu tiêu – Tây thảo", chutri: "Băng lậu" },
  { doiduoc: "Mộc nhĩ thán – Thị bính thán", chutri: "Trường phong hạ huyết; Trĩ xuất huyết" },
  { doiduoc: "Thăng ma – Kinh giới tuệ", chutri: "Xuất huyết trung tiêu, hạ tiêu, băng lậu; Tỳ hư tiết tả; Sốt sản hậu" },
  { doiduoc: "Bạch mao căn – Bạch mao hoa", chutri: "Huyết nhiệt vọng hành gây xuất huyết" },
  { doiduoc: "Phục linh – Phục thần", chutri: "Hỏa thủy vị tế" },
  { doiduoc: "Phục thần – Mạch môn", chutri: "Tâm âm hư dương kháng" },
  { doiduoc: "Sinh táo nhân – Thục táo nhân", chutri: "Tâm huyết hư không dưỡng được thần, hư hỏa thượng viêm gây mất ngủ, tâm quý" },
  { doiduoc: "Toan táo nhân – Bá tử nhân", chutri: "Tâm huyết hư, Tâm dương vượng  mất ngủ; Huyết hư tiện bí; Bệnh tim mạch có hồi hộp, mất ngủ" },
  { doiduoc: "Viễn chí – Thạch xương bồ", chutri: "Rối loạn thần chí sau trúng phong; Tâm thần bất an gây mất ngủ, hay quên" },
  { doiduoc: "Hà thủ ô – Bạch tật lê", chutri: "Can thận hư gây huyễn vựng, mất ngủ, hay quên; Tăng huyết áp, xơ vữa động mạch" },
  { doiduoc: "Cam tùng – Lộc giác sương", chutri: "Lao tâm quá mức làm tinh hao tổn gây chóng mặt, mất ngủ, hay quên; Huyết áp thấp" },
  { doiduoc: "Bách hợp – Tri mẫu", chutri: "Âm hư gây mất ngủ; Tinh thần hốt hoảng không yên" },
  { doiduoc: "Toan táo nhân – Chi tử", chutri: "Tâm hỏa vượng gây mất ngủ, mơ nhiều; Suy nhược mạn" },
  { doiduoc: "Bán hạ - Hạ khô thảo", chutri: "Đàm nhiệt gây ngực phiền, chóng mặt, mất ngủ, đau đầu; Suy nhược mạn" },
  { doiduoc: "Hoàng liên – Nhục quế", chutri: "Mất ngủ do Tâm thận bất giao" },
  { doiduoc: "Hoàng liên – A giao", chutri: "Âm hư hỏa vượng gây tâm phiền mất ngủ; Thấp nhiệt lỵ" },
  { doiduoc: "Nữ trinh tử - Hạn liên thảo", chutri: "Can thận hư gây chóng mặt, mất ngủ, hay quên, tóc bạc sớm; Âm hư hỏa vượng bức huyết vọng hành gây chảy máu mũi, chảy máu răng, thổ huyết, tiện huyết, niệu huyết, băng lậu" },
  { doiduoc: "Bạch vi – Bạch tật lê", chutri: "Can dương thượng kháng gây đau đầu, mất ngủ; Tăng huyết áp" },
  { doiduoc: "Long cốt – Mẫu lệ", chutri: "Âm hư dương kháng làm tâm thần bất an gây mất ngủ, hay quên, ù tai, chóng mặt; Tăng huyết áp; Cửu tả, cửu lỵ; Tiểu không tự chủ, di tinh, hoạt tinh, băng lậu, đới hạ" },
  { doiduoc: "Tử thạch anh – Tử bối xỉ", chutri: "Thần chí không yên, tâm quý chính xung, mất ngủ mơ nhiều, chóng mặt; Tăng huyết áp" },
  { doiduoc: "Long xỉ - Tử bối xỉ", chutri: "Dương không nhập âm gây mất ngủ; Tăng huyết áp" },
  { doiduoc: "Thạch quyết minh – Tử thạch anh", chutri: "Can dương thượng kháng gây chóng mặt, đau đầu, mất ngủ; Tăng huyết áp" },
  { doiduoc: "Tử thạch anh – Thiết lạc", chutri: "Điên, cuồng, giản; Kinh quý, huyễn vựng, thất miên; Tăng huyết áp" },
  { doiduoc: "Thạch quyết minh – Từ thạch", chutri: "Can thận hư, Can dương thượng nhiễu gây chóng mặt, đau đầu, ù tai, mất ngủ mơ nhiều; Tăng huyết áp" },
  { doiduoc: "Tử thạch anh – Từ thạch", chutri: "Thận âm hư, Can dương thượng kháng gây chóng mặt, ù tai, đau đầu, mất ngủ; Tăng huyết áp" },
  { doiduoc: "Tử thạch anh – Bạch thạch anh", chutri: "Tâm phế khí hư gây tâm quý; Ôn dương trị dương nuy, vô sinh nam nữ" },
  { doiduoc: "Trân châu mẫu – Từ châu hoàn", chutri: "Can thận hư, Can dương thượng kháng gây chóng mặt, mắt mờ, ù tai, điếc" },
  { doiduoc: "Chu sa – Hổ phách", chutri: "Tâm thần không yên, mất ngủ mơ nhiều; Rung nhĩ" },
  { doiduoc: "Bạch tật lê – Bạch cương tàm", chutri: "Can dương thượng kháng gây chóng mặt; Đau đầu do đau thần kinh; Nám da" },
  { doiduoc: "Cương tàm – Địa long", chutri: "Phong đàm gây đau đầu mạn tính; Sốt cao co giật; Liệt mặt, đau dây V" },
  { doiduoc: "Toàn yết – Câu đằng", chutri: "Liệt mặt, đau dây V; Tăng huyết áp, xơ vữa động mạch; Phong nhiệt gây đau đầu mạn tính" },
  { doiduoc: "Toàn yết – Ngô công", chutri: "Trúng phong, động kinh, cấp mạn kinh phong; Các chứng lở loét, tràng nhạc; Phong thấp tý; Các chứng đau đầu khó trị" },
  { doiduoc: "Sung úy tử - Thiên ma", chutri: "Động kinh; Đau đầu; Tăng huyết áp" },
  { doiduoc: "Trân châu – Hải sâm", chutri: "Động kinh" },
  { doiduoc: "Uất kim – Bạch phàn", chutri: "Phong đàm gây động kinh, điên cuồng" },
  { doiduoc: "A giao – Quy bản giao – Lộc giác giao", chutri: "Động kinh; Hư lao" },
  { doiduoc: "Bạch chỉ - Cương tàm", chutri: "Đau cung mày do phong nhiệt; Đới hạ; Nám da" },
  { doiduoc: "Sung úy tử - Hạ khô thảo", chutri: "Tăng huyết áp; Xơ vữa động mạch, thiểu năng tuần hoàn nảo, di chứng TBMMN" },
  { doiduoc: "Hoa hòe – Hoàng cầm", chutri: "Tăng huyết áp, xơ vữa động mạch thể Can dương vượng" },
  { doiduoc: "Câu đằng – Ngưu tất", chutri: "Tăng huyết áp do Can dương vượng" },
  { doiduoc: "Mẫu lệ - Cát căn", chutri: "Tăng huyết áp do Can dương vượng" },
  { doiduoc: "Tiên mao – Dâm dương hoắc", chutri: "Tăng huyết áp; Dương hư gây tay chân lạnh, lưng gối lạnh đau, yếu mỏi; Tiền mãn kinh" },
  { doiduoc: "Nhân sâm – Phụ tử", chutri: "Khí hư dục thoát; Quyết âm chứng" },
  { doiduoc: "Phụ tử - Can khương", chutri: "Dương hư dục thoát; Tỳ Vị hư hàn" },
  { doiduoc: "Phụ tử - Bạch thược", chutri: "Đau ngực do Tâm mạch tắc trở gặp hàn phát bệnh; Tỳ Vị hư hàn gây đau bụng; Hàn trệ Can mạch gây đau liên sườn, gan lách to; Thống kinh do hàn; Phong hàn thấp tý" },
  { doiduoc: "Xa tiền thảo – Hạn liên thảo", chutri: "Lâm chứng; Nhiễm trùng tiểu" },
  { doiduoc: "Biển súc – Cù mạch", chutri: "Lâm chứng do thấp nhiệt; Nhiễm trùng tiểu" },
  { doiduoc: "Hồng khúc – Xa tiền tử", chutri: "Tỳ Vị mất kiện vận gây tiêu chảy, lỵ tật, tiểu khó" },
  { doiduoc: "Xích tiểu đậu – Xích phục linh", chutri: "Thấp nhiệt gây phù, tiểu khó; Nhiễm trùng tiểu; Áp xe vú; Lỵ tật" },
  { doiduoc: "Xích phục linh – Xích thược", chutri: "Phù, tiểu khó; Nhiễm trùng tiểu; Ôn bệnh nhập dinh huyết gây tiểu máu, nôn ra máu" },
  { doiduoc: "Hoàng kỳ - Phòng kỷ", chutri: "Phong thủy; Thấp tý; Phù thũng do khí hư thấp thịnh" },
  { doiduoc: "Đại phúc bì – Binh lang", chutri: "Phúc thủy; Khí trệ trung tiêu gây bụng chướng đầy, ợ hơi" },
  { doiduoc: "Ma hoàng – Phù bình", chutri: "Phong thủy; Mề đay có ngứa da do phong hàn" },
  { doiduoc: "Ma hoàng – Thạch cao", chutri: "Phong thủy, chính thủy, thạch thủy; Ho do phế nhiệt" },
  { doiduoc: "Ích trí nhân – Tỳ giải", chutri: "Thận hư gây cao lâm, đới hạ; Tăng uric acid" },
  { doiduoc: "Huyết dư thán – Cửu thái tử", chutri: "Thận dương hư gây đau lưng kèm phù thũng" },
  { doiduoc: "Huyết dư thán – Xa tiền tử", chutri: "Lâm chứng; Tiêu chảy, lỵ" },
  { doiduoc: "Đông qua tử - Điềm qua tử", chutri: "Âm thủy ở ngực gây ngực đầy, ho khạc đàm; Phế ung" },
  { doiduoc: "Đông qua tử - Đông quỳ tử", chutri: "Thủy thũng; Phế ung" },
  { doiduoc: "Đông qua tử - Quất diệp", chutri: "Khí thủy" },
  { doiduoc: "Hạnh nhân – Ý dĩ", chutri: "Phế nuy, Phế ung" },
  { doiduoc: "Đông quỳ tử - Phục linh", chutri: "Thủy thũng" },
  { doiduoc: "Phù hải thạch – Hải kim sa", chutri: "Lâm chứng do thấp nhiệt; Sỏi tiết niệu" },
  { doiduoc: "Kim tiền thảo – Hải kim sa", chutri: "Sỏi niệu; Sỏi mật" },
  { doiduoc: "Hoạt thạch – Phù hải thạch", chutri: "Thạch lâm; Tăng sinh tiền liệt tuyến lành tính" },
  { doiduoc: "Phù hải thạch – Ngõa lăng tử", chutri: "Sỏi mật, sỏi niệu; Gan lách to" },
  { doiduoc: "Ngõa lăng tử - Hoạt thạch", chutri: "Sỏi niệu" },
  { doiduoc: "Ngõa lăng tử - Ngư não thạch", chutri: "Sỏi mật, sỏi niệu" },
  { doiduoc: "Kê nội kim – Mang tiêu", chutri: "Sỏi niệu" },
  { doiduoc: "Huyết dư thán – Lục nhất tán – Ý dĩ", chutri: "Dự phòng sỏi niệu tái phát" },
  { doiduoc: "Triết bối mẫu- Hạ khô thảo", chutri: "Tràng nhạc" },
  { doiduoc: "Huyền sâm – Mẫu lệ", chutri: "Đàm kết gây tràng nhạc, anh lựu, đàm hạch" },
  { doiduoc: "Hải tảo – Côn bố", chutri: "Tràng nhạc, anh lựu, đàm hạch; Xơ vữa động mạch, di chứng trúng phong; Ung thư dạ dày ruột; U của vú và phần phụ" },
  { doiduoc: "Quất hạch – Lệ chi hạch", chutri: "Âm nang, tinh hoàn sưng đau; Bụng dưới đau do khí trệ; Tích khối ở bụng dưới; Hư hàn đới hạ" },
  { doiduoc: "Hợp hoan bì – Bạch tật lê", chutri: "Gan lách to, xơ gan, viêm gan mạn" },
  { doiduoc: "Đỗ trọng – Tục đoạn", chutri: "Can Thận hư gây lưng gối đau mỏi yếu; Phong thấp tý gây đau lưng gối; Băng lậu, động thai" },
  { doiduoc: "Thục địa – Tế tân", chutri: "Đau lưng" },
  { doiduoc: "Tục đoạn – Hoàng tinh", chutri: "Can thận hư" },
  { doiduoc: "Bạch tật lê – Sa uyển tử", chutri: "Can thận hư gây mắt mờ; Thận hư đau lưng; Đới hạ" },
  { doiduoc: "Tàm sa – Dạ minh sa", chutri: "Can nhiệt gây mắt đỏ" },
  { doiduoc: "Kỷ tử - Cúc hoa", chutri: "Can thận hư gây nhìn mờ" },
  { doiduoc: "Cẩu tích – Công lao diệp", chutri: "Can thận hư gây đau lưng, mỏi gối, ù tai; Phong thấp tý gây đau lưng" },
  { doiduoc: "Nữ trinh tử - Tục đoạn", chutri: "Lãnh cảm" },
  { doiduoc: "Đảng sâm – Hoàng kỳ", chutri: "Tỳ Vị hư nhược; Khí hư gây ma mộc; Thăng dương cử hãm" },
  { doiduoc: "Thăng ma – Sài hồ", chutri: "Sa tạng phủ" },
  { doiduoc: "Tang diệp – Hắc chi ma", chutri: "Âm hư huyết táo gây chóng mặt, nhìn mờ; Tóc bạc sớm" },
  { doiduoc: "Bạch truật – Hoàng cầm", chutri: "Thấp nhiệt nội uẩn; Động thai, sẩy thai liên tiếp" },
  { doiduoc: "Tang chi – Tang ký sinh", chutri: "Phong thấp tý gây đau lưng gối; Tăng huyết áp, bệnh mạch vành" },
  { doiduoc: "Khương hoạt – Độc hoạt", chutri: "Phong tý; Ngoại cảm phong hàn; Lịch tiết phong" },
  { doiduoc: "Hải đồng bì – Tần giao", chutri: "Phong thấp tý gây đau, tay chân co quắp; Di chứng bại não" },
  { doiduoc: "Hải phong đằng – Lạc thạch đằng", chutri: "Phong thấp tý; Bán thân bất toại" },
  { doiduoc: "Hải đồng bì – Hy thiêm thảo", chutri: "Phong thấp tý; Bán thân bất toại; Di chứng bại não" },
  { doiduoc: "Ngô thù du – Mộc qua", chutri: "Hàn thấp hoặc thử thấp gây co rút cơ; Chi dưới vô lực; Sán khí bụng đau; Cước khí thượng xung gây buồn nôn, nôn, tâm quý" },
  { doiduoc: "Bạch thược – Cam thảo", chutri: "Khí huyết bất hòa gây co quắp; Huyết hư gây đau đầu, đau dây V; Vị quản thống" },
];
