window.treatmentTerms = [
  "Tân ôn giải biểu",
  "Phát hãn",
  "Trừ thấp giải biểu",
  "Tân lương giải biểu",
  "Tả hạ",
  "Thanh nhiệt tả hỏa",
  "Thanh nhiệt lương huyết",
  "Thanh nhiệt dưỡng âm",
  "Thanh Phế nhiệt",
  "Thanh Tâm nhiệt",
  "Thanh Can nhiệt",
  "Thanh Thận nhiệt",
  "Thanh Vị nhiệt",
  "Thanh nhiệt táo thấp",
  "Thanh nhiệt Đại trường",
  "Thanh nhiệt Tiểu trường",
  "Khai khiếu tỉnh thần",
  "Phương hương hóa thấp",
  "Lợi thủy thẩm thấp",
  "Kiện tỳ, lợi thủy, thẩm thấp",
  "Lợi thủy, chỉ huyết",
  "Lợi thủy, trừ thấp nhiệt, chỉ huyết, bài thạch",
  "Trừ phong thấp kiêm hàn",
  "Trừ phong thấp",
  "Trừ hàn thấp",
  "Trừ phong thấp, thông kinh",
  "Trừ phong thấp, bổ can thận",
  "Trừ phong thấp, chỉ thống",
  "Ôn Thận dương, tán hàn",
  "Ôn Tỳ Vị, tán hàn",
  "Trọng trấn an thần",
  "Dưỡng tâm an thần",
  "Tiềm Can dương, an thần",
  "Lý khí Tỳ Vị",
  "Lý Can khí",
  "Hoạt huyết chỉ thống (ôn dược)",
  "Phá huyết khử ứ",
  "Thông kinh hoạt lạc",
  "Hoạt huyết bổ huyết (lương dược)",
  "Chỉ huyết trường phủ",
  "Chỉ huyết niệu dục",
  "Chỉ huyết bào cung",
  "Chỉ khái",
  "Giáng Phế khí, bình suyễn",
  "Ôn hóa hàn đàm, chỉ khái",
  "Thanh hóa đàm nhiệt, chỉ khái",
  "Hóa đàm trọc",
  "Hóa đàm nhuyễn kiên",
  "Trừ phong đàm",
  "Trừ đàm khai khiếu",
  "Bổ Tỳ khí",
  "Bổ Phế khí",
  "Bổ dương kiêm bổ tinh",
  "Bổ Thận cố Bàng quang",
  "Bổ Thận an thai",
  "Bổ huyết",
  "Cố tinh, liễm can âm",
  "Dưỡng Phế âm",
  "Dưỡng Tâm âm",
  "Dưỡng Can âm",
  "Dưỡng Vị âm",
  "Dưỡng Thận âm",
  "Liễm Phế khí",
  "Chỉ hãn",
  "Sáp trường chỉ tả",
  "Cố Bàng quang sáp niệu",
  "Cố tinh",
  "Tiêu thực (ngũ cốc, hoa quả)",
  "Tiêu thực (ngũ cốc, rượu)",
  "Tiêu thực (thịt, dầu mỡ)",
  "Sơ Can giải uất",
  "Hoạt huyết nhu Can",
  "Thanh Can tả hỏa",
  "Lương Can huyết",
  "Bình Can dương",
  "Tức Can phong",
  "Bổ Can huyết",
  "Bổ Can âm",
  "Ôn Can kinh",
  "Trừ thấp nhiệt",
  "Bổ Tâm khí",
  "Bổ Tâm dương",
  "Bổ Tâm huyết",
  "Tả Tâm hỏa",
  "Hoạt huyết ôn kinh",
  "Hành khí",
  "Giáng khí",
  "Thăng Tỳ khí",
  "Bổ Tỳ dương",
  "Ôn dương",
  "Hóa thấp",
  "Trừ thấp",
  "Trừ đàm",
  "Hóa đàm",
  "Trừ thấp nhiệt",
  "Tả Vị hỏa",
  "Giáng khí chỉ ẩu",
  "Hành khí tán hàn",
  "Hòa trung",
  "Bổ Phế âm",
  "Sinh tân, thanh hư nhiệt",
  "Giải biểu",
  "Trừ đàm thấp",
  "Thanh nhiệt",
  "Trừ đàm trọc",
  "Đàm khó khạc",
  "Đàm máu",
  "Hàn đàm",
  "Nhiệt đàm",
  "Bổ Thận dương",
  "Bổ Thận khí",
  "Bổ Thận âm",
  "Bổ Thận tinh",
  "Thanh nhiệt, hành tân",
  "Chỉ tả",
  "Ngoại thấp ở thượng tiêu",
  "Ngoại thấp ở trung tiêu",
  "Ngoại thấp ở hạ tiêu",
  "Thấp tại kinh lạc",
  "Thấp tại da",
  "Thấp phạm Tỳ Vị",
  "Thấp nhiệt",
  "Đàm tại Tỳ Vị",
  "Đàm tại Phế",
  "Đàm tại Tâm",
  "Hàn tại kinh lạc",
  "Hàn tại lý",
  "Tán phong hàn",
  "Tán phong nhiệt",
  "Phong hàn phạm kinh lạc",
  "Nội phong",
  "Tả hỏa",
  "Lương huyết",
  "Thanh thử, Nhuận Thận",
  "Nhuận Phế"
];
