export function renderStep3(root) {
  fetch('./partials/step3.html')
    .then(res => res.text())
    .then(html => {
      root.innerHTML = html;
      populateStep3();

      document.getElementById("btn-back-step2").onclick = () => window.location.hash = "#/step2";
      document.getElementById("btn-save-next-step3").onclick = () => {
        saveStep3();
        window.location.hash = "#/step4";
      };

      document.getElementById("btn-auto-tree").onclick = autoGenerateDiagnosticTree;
      document.getElementById("btn-auto-classic").onclick = autoSuggestClassicSyndrome;
    });
}

// Lịch sử hội chứng các lần khám trước + nạp lại field hiện tại
function populateStep3() {
  const data = JSON.parse(localStorage.getItem("currentData") || "{}");
  const history = data.steps?.step2?.history || [];

  // Lịch sử hội chứng
  const ul = document.getElementById("past-syndrome-list");
  ul.innerHTML = "";
  history.forEach((entry, index) => {
    const label = entry?.syndrome?.final || entry?.syndrome?.model || "(Chưa ghi)";
    const li = document.createElement("li");
    li.textContent = `Lần ${index + 1} – ${label}`;
    ul.appendChild(li);
  });

  // Field hiện tại
  const current = data.steps?.step3 || {};
  document.getElementById("syndrome-model").value = current.model || "";
  document.getElementById("syndrome-classic").value = current.classic || "";
  document.getElementById("syndrome-final").value = current.final || "";
}

function saveStep3() {
  const model = document.getElementById("syndrome-model").value.trim();
  const classic = document.getElementById("syndrome-classic").value.trim();
  const final = document.getElementById("syndrome-final").value.trim();

  const key = localStorage.getItem("currentPatient");
  if (!key) return alert("Chưa chọn hồ sơ!");

  const data = JSON.parse(localStorage.getItem(key) || "{}");
  data.steps = data.steps || {};
  data.steps.step3 = { model, classic, final };

  localStorage.setItem(key, JSON.stringify(data));
  localStorage.setItem("currentData", JSON.stringify(data));
}

async function autoSuggestClassicSyndrome() {
  const data = JSON.parse(localStorage.getItem("currentData") || "{}");
  const rawText = data.steps?.step1?.symptoms || "";
  const outputBox = document.getElementById("syndrome-classic");

  if (!rawText.trim()) {
    alert("⚠️ Chưa có mô tả triệu chứng ở bước 1.");
    return;
  }

  outputBox.value = "⏳ Đang phân tích bằng GPT, vui lòng chờ...";

  const prompt = `
Bạn là chuyên gia Y học cổ truyền.

Dưới đây là mô tả bệnh cảnh của một bệnh nhân, bao gồm hỏi bệnh, triệu chứng và dấu hiệu lâm sàng:

"""
${rawText}
"""

🎯 YÊU CẦU:

1. Dựa trên mô tả trên, hãy xác định **hội chứng Y học cổ truyền phù hợp nhất** (có thể là 1 hoặc nhiều hội chứng phối hợp).
2. Với mỗi hội chứng, nêu tên hội chứng và giải thích ngắn gọn lý do chọn (triệu chứng nào dẫn đến hội chứng đó).
3. Trình bày kết quả như sau (chỉ văn bản, không mã hóa, không JSON):

📌 Hội chứng: ...
🔍 Lý do: ...
📌 Hội chứng: ...
🔍 Lý do: ...

❗Không thêm bất kỳ phần mở đầu, lời giải thích nào ngoài kết quả.
`.trim();

  try {
    const res = await fetch("https://gpt-api-19xu.onrender.com/gpt.php", {
      method: "POST",
      body: JSON.stringify({ prompt })
    });

    const gptJson = await res.json();
    const gptText = gptJson?.choices?.[0]?.message?.content || "";

    if (!gptText.trim()) {
      outputBox.value = "⚠️ GPT không xác định được hội chứng phù hợp.";
      return;
    }

    outputBox.value = gptText.trim();

    data.steps = data.steps || {};
    data.steps.step3 = {
      ...data.steps.step3,
      classic: gptText.trim()
    };
    localStorage.setItem("currentData", JSON.stringify(data));

  } catch (err) {
    outputBox.value = "❌ Lỗi khi gọi GPT API.";
    console.error("❌ Lỗi khi gọi GPT API:", err);
  }
}

async function autoGenerateDiagnosticTree() {
  const data = JSON.parse(localStorage.getItem("currentData") || "{}");
  const symptoms = data.steps?.step2?.symptoms || [];
  const rawSymptoms = data.steps?.step1?.symptoms || "";
  const outputBoxModel = document.getElementById("syndrome-model");

  if (!symptoms.length) {
    alert("⚠️ Chưa có dữ liệu VAS từ bước 2.");
    return;
  }
  if (outputBoxModel) outputBoxModel.value = "⏳ Đang phân tích, vui lòng chờ...";

  // Sắp xếp theo VAS giảm dần
  const sorted = [...symptoms].sort((a, b) => b.vas - a.vas);
  const symptomList = sorted.map(s => `– ${s.symptom} (VAS: ${s.vas})`).join("\n");

  // Thu thập trả lời câu hỏi phụ nếu có
  const extraAnswers = collectExtraAnswers();
  let extraText = "";

  if (extraAnswers.length > 0) {
    extraText = "\n\n🔶 **THÔNG TIN BỔ SUNG TỪ NGƯỜI DÙNG:**\n" +
      extraAnswers.map(e => `▫ ${e.question}: ${e.answer}`).join("\n");
  }

  // Prompt
  const basePrompt = `Bạn là một bác sĩ Y học cổ truyền có kinh nghiệm chẩn đoán bệnh theo biện chứng luận trị.  
Tôi sẽ cung cấp danh sách các triệu chứng và điểm VAS (mức độ nặng nhẹ).  
Hãy làm theo các bước sau để xây dựng sơ đồ biện chứng 6 bước cho hội chứng YHCT:

🔶 **DANH SÁCH TRIỆU CHỨNG VÀ VAS:**  
${symptomList}
${rawSymptoms}
${extraText}
[...các bước hướng dẫn chi tiết đã có trong file index gốc, nếu muốn copy đủ, bạn paste từ index gốc vào đây!]
`;

  const res = await fetch("https://gpt-api-19xu.onrender.com/gpt.php", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ prompt: basePrompt })
  });

  const result = await res.json();
  const reply = result.choices?.[0]?.message?.content || "Không nhận được phản hồi từ GPT.";

  // Tìm các followup questions (dòng bắt đầu bằng ▫ hoặc ❓)
  const followupQuestions = reply
    .split("\n")
    .filter(line => line.trim().startsWith("▫") || line.trim().startsWith("❓"))
    .map(line => ({
      question: line.replace(/^(\▫|❓)\s*/, "").trim()
    }));

  renderExtraQuestions(followupQuestions);
  localStorage.setItem("extraFollowupQuestions", JSON.stringify(followupQuestions));
  if (outputBoxModel) {
    outputBoxModel.value = reply;
  }
}

// Render các câu hỏi followup
function renderExtraQuestions(questions) {
  const container = document.getElementById("tree-extra-questions");
  container.innerHTML = "";
  if (!questions || !questions.length) return;

  questions.forEach((q, index) => {
    const wrapper = document.createElement("div");
    wrapper.className = "mb-3";

    const label = document.createElement("label");
    label.textContent = `❓ ${q.question}`;
    label.className = "block text-sm font-medium text-gray-700 mb-1";

    const input = document.createElement("input");
    input.type = "text";
    input.name = `extra-${index}`;
    input.className = "extra-question-input w-full border rounded px-3 py-1 focus:outline-none focus:ring focus:ring-blue-200";
    input.placeholder = "Nhập câu trả lời...";

    wrapper.appendChild(label);
    wrapper.appendChild(input);
    container.appendChild(wrapper);
  });
}

// Lấy trả lời các câu hỏi followup
function collectExtraAnswers() {
  const inputs = document.querySelectorAll(".extra-question-input");
  const answers = [];
  inputs.forEach((input, index) => {
    const questionLabel = input.previousElementSibling?.textContent || `Câu hỏi ${index + 1}`;
    const cleanQuestion = questionLabel.replace(/^❓\s*/, "").trim();
    const answer = input.value.trim();
    if (answer) {
      answers.push({ question: cleanQuestion, answer });
    }
  });
  return answers;
}
